version: '3'
services:
  jetty:
    image: jetty
    container_name: builder_jetty
    volumes:
    - ./site/ROOT.war:/var/lib/jetty/webapps/ROOT.war
    - ./site/application.conf:/var/lib/jetty/webapps/application.conf
    - ./or-tools/:/var/lib/jetty/or-tools/
    - ./site/allRegions.json:/var/lib/jetty/allRegions.json

    ports:
    - "8080:8080"

  nginx:
    image: nginx
    container_name: builder_nginx
    depends_on:
    - jetty
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./site/js:/etc/nginx/html/js
    - ./site/css:/etc/nginx/html/css
    - ./nginx/letsencrypt/:/etc/letsencrypt/
    - ./nginx/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    ports:
    - "80:80"
    - "443:443"
