ALTER TABLE agtagenttypes DISABLE TRIGGER ALL;
ALTER TABLE agtagents DISABLE TRIGGER ALL;
ALTER TABLE agtresearchagents DISABLE TRIGGER ALL;
ALTER TABLE certcerts DISABLE TRIGGER ALL;
ALTER TABLE certmasteries DISABLE TRIGGER ALL;
ALTER TABLE certskills DISABLE TRIGGER ALL;
ALTER TABLE chrancestries DISABLE TRIGGER ALL;
ALTER TABLE chrattributes DISABLE TRIGGER ALL;
ALTER TABLE chrbloodlines DISABLE TRIGGER ALL;
ALTER TABLE chrfactions DISABLE TRIGGER ALL;
ALTER TABLE chrraces DISABLE TRIGGER ALL;
ALTER TABLE crpactivities DISABLE TRIGGER ALL;
ALTER TABLE crpnpccorporationdivisions DISABLE TRIGGER ALL;
ALTER TABLE crpnpccorporationresearchfields DISABLE TRIGGER ALL;
ALTER TABLE crpnpccorporationtrades DISABLE TRIGGER ALL;
ALTER TABLE crpnpccorporations DISABLE TRIGGER ALL;
ALTER TABLE crpnpcdivisions DISABLE TRIGGER ALL;
ALTER TABLE dgmattributecategories DISABLE TRIGGER ALL;
ALTER TABLE dgmattributetypes DISABLE TRIGGER ALL;
ALTER TABLE dgmtypeattributes DISABLE TRIGGER ALL;
ALTER TABLE eveicons DISABLE TRIGGER ALL;
ALTER TABLE eveunits DISABLE TRIGGER ALL;
ALTER TABLE industryactivity DISABLE TRIGGER ALL;
ALTER TABLE invmetagroups DISABLE TRIGGER ALL;
ALTER TABLE invmetatypes DISABLE TRIGGER ALL;
ALTER TABLE invtypematerials DISABLE TRIGGER ALL;
ALTER TABLE dgmeffects DISABLE TRIGGER ALL;
ALTER TABLE dgmexpressions DISABLE TRIGGER ALL;
ALTER TABLE dgmtypeeffects DISABLE TRIGGER ALL;
ALTER TABLE evegraphics DISABLE TRIGGER ALL;
ALTER TABLE industryactivitymaterials DISABLE TRIGGER ALL;
ALTER TABLE industryactivityprobabilities DISABLE TRIGGER ALL;
ALTER TABLE industryactivityproducts DISABLE TRIGGER ALL;
ALTER TABLE industryactivityraces DISABLE TRIGGER ALL;
ALTER TABLE industryactivityskills DISABLE TRIGGER ALL;
ALTER TABLE industryblueprints DISABLE TRIGGER ALL;
ALTER TABLE invcategories DISABLE TRIGGER ALL;
ALTER TABLE invcontrabandtypes DISABLE TRIGGER ALL;
ALTER TABLE invcontroltowerresourcepurposes DISABLE TRIGGER ALL;
ALTER TABLE invcontroltowerresources DISABLE TRIGGER ALL;
ALTER TABLE invflags DISABLE TRIGGER ALL;
ALTER TABLE invgroups DISABLE TRIGGER ALL;
ALTER TABLE invitems DISABLE TRIGGER ALL;
ALTER TABLE invmarketgroups DISABLE TRIGGER ALL;
ALTER TABLE invnames DISABLE TRIGGER ALL;
ALTER TABLE invpositions DISABLE TRIGGER ALL;
ALTER TABLE invtraits DISABLE TRIGGER ALL;
ALTER TABLE invtypereactions DISABLE TRIGGER ALL;
ALTER TABLE maplocationscenes DISABLE TRIGGER ALL;
ALTER TABLE ramassemblylinestations DISABLE TRIGGER ALL;
ALTER TABLE raminstallationtypecontents DISABLE TRIGGER ALL;
ALTER TABLE staservices DISABLE TRIGGER ALL;
ALTER TABLE stastationtypes DISABLE TRIGGER ALL;
ALTER TABLE invtypes DISABLE TRIGGER ALL;
ALTER TABLE invuniquenames DISABLE TRIGGER ALL;
ALTER TABLE invvolumes DISABLE TRIGGER ALL;
ALTER TABLE mapcelestialstatistics DISABLE TRIGGER ALL;
ALTER TABLE mapconstellationjumps DISABLE TRIGGER ALL;
ALTER TABLE mapconstellations DISABLE TRIGGER ALL;
ALTER TABLE mapdenormalize DISABLE TRIGGER ALL;
ALTER TABLE mapjumps DISABLE TRIGGER ALL;
ALTER TABLE maplandmarks DISABLE TRIGGER ALL;
ALTER TABLE maplocationwormholeclasses DISABLE TRIGGER ALL;
ALTER TABLE mapregionjumps DISABLE TRIGGER ALL;
ALTER TABLE mapregions DISABLE TRIGGER ALL;
ALTER TABLE mapsolarsystemjumps DISABLE TRIGGER ALL;
ALTER TABLE mapsolarsystems DISABLE TRIGGER ALL;
ALTER TABLE mapuniverse DISABLE TRIGGER ALL;
ALTER TABLE planetschematics DISABLE TRIGGER ALL;
ALTER TABLE planetschematicspinmap DISABLE TRIGGER ALL;
ALTER TABLE planetschematicstypemap DISABLE TRIGGER ALL;
ALTER TABLE ramactivities DISABLE TRIGGER ALL;
ALTER TABLE ramassemblylinetypedetailpercategory DISABLE TRIGGER ALL;
ALTER TABLE ramassemblylinetypedetailpergroup DISABLE TRIGGER ALL;
ALTER TABLE ramassemblylinetypes DISABLE TRIGGER ALL;
ALTER TABLE skinlicense DISABLE TRIGGER ALL;
ALTER TABLE skinmaterials DISABLE TRIGGER ALL;
ALTER TABLE skinship DISABLE TRIGGER ALL;
ALTER TABLE skins DISABLE TRIGGER ALL;
ALTER TABLE staoperationservices DISABLE TRIGGER ALL;
ALTER TABLE staoperations DISABLE TRIGGER ALL;
ALTER TABLE stastations DISABLE TRIGGER ALL;
ALTER TABLE translationtables DISABLE TRIGGER ALL;
ALTER TABLE trntranslationcolumns DISABLE TRIGGER ALL;
ALTER TABLE trntranslationlanguages DISABLE TRIGGER ALL;
ALTER TABLE trntranslations DISABLE TRIGGER ALL;
ALTER TABLE warcombatzonesystems DISABLE TRIGGER ALL;
ALTER TABLE warcombatzones DISABLE TRIGGER ALL;



TRUNCATE agtagenttypes CASCADE;
TRUNCATE agtagents CASCADE;
TRUNCATE agtresearchagents CASCADE;
TRUNCATE certcerts CASCADE;
TRUNCATE certmasteries CASCADE;
TRUNCATE certskills CASCADE;
TRUNCATE chrancestries CASCADE;
TRUNCATE chrattributes CASCADE;
TRUNCATE chrbloodlines CASCADE;
TRUNCATE chrfactions CASCADE;
TRUNCATE chrraces CASCADE;
TRUNCATE crpactivities CASCADE;
TRUNCATE crpnpccorporationdivisions CASCADE;
TRUNCATE crpnpccorporationresearchfields CASCADE;
TRUNCATE crpnpccorporationtrades CASCADE;
TRUNCATE crpnpccorporations CASCADE;
TRUNCATE crpnpcdivisions CASCADE;
TRUNCATE dgmattributecategories CASCADE;
TRUNCATE dgmattributetypes CASCADE;
TRUNCATE dgmeffects CASCADE;
TRUNCATE dgmexpressions CASCADE;
TRUNCATE dgmtypeattributes CASCADE;
TRUNCATE dgmtypeeffects CASCADE;
TRUNCATE evegraphics CASCADE;
TRUNCATE eveicons CASCADE;
TRUNCATE eveunits CASCADE;
TRUNCATE industryactivity CASCADE;
TRUNCATE industryactivitymaterials CASCADE;
TRUNCATE industryactivityprobabilities CASCADE;
TRUNCATE industryactivityproducts CASCADE;
TRUNCATE industryactivityraces CASCADE;
TRUNCATE industryactivityskills CASCADE;
TRUNCATE industryblueprints CASCADE;
TRUNCATE invcategories CASCADE;
TRUNCATE invcontrabandtypes CASCADE;
TRUNCATE invcontroltowerresourcepurposes CASCADE;
TRUNCATE invcontroltowerresources CASCADE;
TRUNCATE invflags CASCADE;
TRUNCATE invgroups CASCADE;
TRUNCATE invitems CASCADE;
TRUNCATE invmarketgroups CASCADE;
TRUNCATE invmetagroups CASCADE;
TRUNCATE invmetatypes CASCADE;
TRUNCATE invnames CASCADE;
TRUNCATE invpositions CASCADE;
TRUNCATE invtraits CASCADE;
TRUNCATE invtypematerials CASCADE;
TRUNCATE invtypereactions CASCADE;
TRUNCATE invtypes CASCADE;
TRUNCATE invuniquenames CASCADE;
TRUNCATE invvolumes CASCADE;
TRUNCATE mapcelestialstatistics CASCADE;
TRUNCATE mapconstellationjumps CASCADE;
TRUNCATE mapconstellations CASCADE;
TRUNCATE mapdenormalize CASCADE;
TRUNCATE mapjumps CASCADE;
TRUNCATE maplandmarks CASCADE;
TRUNCATE maplocationscenes CASCADE;
TRUNCATE maplocationwormholeclasses CASCADE;
TRUNCATE mapregionjumps CASCADE;
TRUNCATE mapregions CASCADE;
TRUNCATE mapsolarsystemjumps CASCADE;
TRUNCATE mapsolarsystems CASCADE;
TRUNCATE mapuniverse CASCADE;
TRUNCATE planetschematics CASCADE;
TRUNCATE planetschematicspinmap CASCADE;
TRUNCATE planetschematicstypemap CASCADE;
TRUNCATE ramactivities CASCADE;
TRUNCATE ramassemblylinestations CASCADE;
TRUNCATE ramassemblylinetypedetailpercategory CASCADE;
TRUNCATE ramassemblylinetypedetailpergroup CASCADE;
TRUNCATE ramassemblylinetypes CASCADE;
TRUNCATE raminstallationtypecontents CASCADE;
TRUNCATE skinlicense CASCADE;
TRUNCATE skinmaterials CASCADE;
TRUNCATE skinship CASCADE;
TRUNCATE skins CASCADE;
TRUNCATE staoperationservices CASCADE;
TRUNCATE staoperations CASCADE;
TRUNCATE staservices CASCADE;
TRUNCATE stastationtypes CASCADE;
TRUNCATE stastations CASCADE;
TRUNCATE translationtables CASCADE;
TRUNCATE trntranslationcolumns CASCADE;
TRUNCATE trntranslationlanguages CASCADE;
TRUNCATE trntranslations CASCADE;
TRUNCATE warcombatzonesystems CASCADE;
TRUNCATE warcombatzones CASCADE;



INSERT INTO agtagenttypes SELECT * FROM evesde."agtAgentTypes";
INSERT INTO agtagents SELECT * FROM evesde."agtAgents";
INSERT INTO agtresearchagents SELECT * FROM evesde."agtResearchAgents";
INSERT INTO certcerts SELECT * FROM evesde."certCerts";
INSERT INTO certmasteries SELECT * FROM evesde."certMasteries";
INSERT INTO certskills SELECT * FROM evesde."certSkills";
INSERT INTO chrancestries SELECT * FROM evesde."chrAncestries";
INSERT INTO chrattributes SELECT * FROM evesde."chrAttributes";
INSERT INTO chrbloodlines SELECT * FROM evesde."chrBloodlines";
INSERT INTO chrfactions SELECT * FROM evesde."chrFactions";
INSERT INTO chrraces SELECT * FROM evesde."chrRaces";
INSERT INTO crpactivities SELECT * FROM evesde."crpActivities";
INSERT INTO crpnpccorporationdivisions SELECT * FROM evesde."crpNPCCorporationDivisions";
INSERT INTO crpnpccorporationresearchfields SELECT * FROM evesde."crpNPCCorporationResearchFields";
INSERT INTO crpnpccorporationtrades SELECT * FROM evesde."crpNPCCorporationTrades";
INSERT INTO crpnpccorporations SELECT * FROM evesde."crpNPCCorporations";
INSERT INTO crpnpcdivisions SELECT * FROM evesde."crpNPCDivisions";
INSERT INTO dgmattributecategories SELECT * FROM evesde."dgmAttributeCategories";
INSERT INTO dgmattributetypes SELECT * FROM evesde."dgmAttributeTypes";
INSERT INTO dgmeffects SELECT * FROM evesde."dgmEffects";
INSERT INTO dgmexpressions SELECT * FROM evesde."dgmExpressions";
INSERT INTO dgmtypeattributes SELECT * FROM evesde."dgmTypeAttributes";
INSERT INTO dgmtypeeffects SELECT * FROM evesde."dgmTypeEffects";
INSERT INTO evegraphics SELECT * FROM evesde."eveGraphics";
INSERT INTO eveicons SELECT * FROM evesde."eveIcons";
INSERT INTO eveunits SELECT * FROM evesde."eveUnits";
INSERT INTO industryactivity SELECT * FROM evesde."industryActivity";
INSERT INTO industryactivitymaterials SELECT * FROM evesde."industryActivityMaterials";
INSERT INTO industryactivityprobabilities SELECT * FROM evesde."industryActivityProbabilities";
INSERT INTO industryactivityproducts SELECT * FROM evesde."industryActivityProducts";
INSERT INTO industryactivityraces SELECT * FROM evesde."industryActivityRaces";
INSERT INTO industryactivityskills SELECT * FROM evesde."industryActivitySkills";
INSERT INTO industryblueprints SELECT * FROM evesde."industryBlueprints";
INSERT INTO invcategories SELECT * FROM evesde."invCategories";
INSERT INTO invcontrabandtypes SELECT * FROM evesde."invContrabandTypes";
INSERT INTO invcontroltowerresourcepurposes SELECT * FROM evesde."invControlTowerResourcePurposes";
INSERT INTO invcontroltowerresources SELECT * FROM evesde."invControlTowerResources";
INSERT INTO invflags SELECT * FROM evesde."invFlags";
INSERT INTO invgroups SELECT * FROM evesde."invGroups";
INSERT INTO invitems SELECT * FROM evesde."invItems";
INSERT INTO invmarketgroups SELECT * FROM evesde."invMarketGroups";
INSERT INTO invmetagroups SELECT * FROM evesde."invMetaGroups";
INSERT INTO invmetatypes SELECT * FROM evesde."invMetaTypes";
INSERT INTO invnames SELECT * FROM evesde."invNames";
INSERT INTO invpositions SELECT * FROM evesde."invPositions";
INSERT INTO invtraits SELECT * FROM evesde."invTraits";
INSERT INTO invtypematerials SELECT * FROM evesde."invTypeMaterials";
INSERT INTO invtypereactions SELECT * FROM evesde."invTypeReactions";
INSERT INTO invtypes SELECT * FROM evesde."invTypes";
INSERT INTO invuniquenames SELECT * FROM evesde."invUniqueNames";
INSERT INTO invvolumes SELECT * FROM evesde."invVolumes";
INSERT INTO mapcelestialstatistics SELECT * FROM evesde."mapCelestialStatistics";
INSERT INTO mapconstellationjumps SELECT * FROM evesde."mapConstellationJumps";
INSERT INTO mapconstellations SELECT * FROM evesde."mapConstellations";
INSERT INTO mapdenormalize SELECT * FROM evesde."mapDenormalize";
INSERT INTO mapjumps SELECT * FROM evesde."mapJumps";
INSERT INTO maplandmarks SELECT * FROM evesde."mapLandmarks";
INSERT INTO maplocationscenes SELECT * FROM evesde."mapLocationScenes";
INSERT INTO maplocationwormholeclasses SELECT * FROM evesde."mapLocationWormholeClasses";
INSERT INTO mapregionjumps SELECT * FROM evesde."mapRegionJumps";
INSERT INTO mapregions SELECT * FROM evesde."mapRegions";
INSERT INTO mapsolarsystemjumps SELECT * FROM evesde."mapSolarSystemJumps";
INSERT INTO mapsolarsystems SELECT * FROM evesde."mapSolarSystems";
INSERT INTO mapuniverse SELECT * FROM evesde."mapUniverse";
INSERT INTO planetschematics SELECT * FROM evesde."planetSchematics";
INSERT INTO planetschematicspinmap SELECT * FROM evesde."planetSchematicsPinMap";
INSERT INTO planetschematicstypemap SELECT * FROM evesde."planetSchematicsTypeMap";
INSERT INTO ramactivities SELECT * FROM evesde."ramActivities";
INSERT INTO ramassemblylinestations SELECT * FROM evesde."ramAssemblyLineStations";
INSERT INTO ramassemblylinetypedetailpercategory SELECT * FROM evesde."ramAssemblyLineTypeDetailPerCategory";
INSERT INTO ramassemblylinetypedetailpergroup SELECT * FROM evesde."ramAssemblyLineTypeDetailPerGroup";
INSERT INTO ramassemblylinetypes SELECT * FROM evesde."ramAssemblyLineTypes";
INSERT INTO raminstallationtypecontents SELECT * FROM evesde."ramInstallationTypeContents";
INSERT INTO skinlicense SELECT * FROM evesde."skinLicense";
INSERT INTO skinmaterials SELECT * FROM evesde."skinMaterials";
INSERT INTO skinship SELECT * FROM evesde."skinShip";
INSERT INTO skins SELECT * FROM evesde."skins";
INSERT INTO staoperationservices SELECT * FROM evesde."staOperationServices";
INSERT INTO staoperations SELECT * FROM evesde."staOperations";
INSERT INTO staservices SELECT * FROM evesde."staServices";
INSERT INTO stastationtypes SELECT * FROM evesde."staStationTypes";
INSERT INTO stastations SELECT * FROM evesde."staStations";
INSERT INTO translationtables SELECT * FROM evesde."translationTables";
INSERT INTO trntranslationcolumns SELECT * FROM evesde."trnTranslationColumns";
INSERT INTO trntranslationlanguages SELECT * FROM evesde."trnTranslationLanguages";
INSERT INTO trntranslations SELECT * FROM evesde."trnTranslations";
INSERT INTO warcombatzonesystems SELECT * FROM evesde."warCombatZoneSystems";
INSERT INTO warcombatzones SELECT * FROM evesde."warCombatZones";



ALTER TABLE agtagenttypes ENABLE TRIGGER ALL;
ALTER TABLE agtagents ENABLE TRIGGER ALL;
ALTER TABLE agtresearchagents ENABLE TRIGGER ALL;
ALTER TABLE certcerts ENABLE TRIGGER ALL;
ALTER TABLE certmasteries ENABLE TRIGGER ALL;
ALTER TABLE certskills ENABLE TRIGGER ALL;
ALTER TABLE chrancestries ENABLE TRIGGER ALL;
ALTER TABLE chrattributes ENABLE TRIGGER ALL;
ALTER TABLE chrbloodlines ENABLE TRIGGER ALL;
ALTER TABLE chrfactions ENABLE TRIGGER ALL;
ALTER TABLE chrraces ENABLE TRIGGER ALL;
ALTER TABLE crpactivities ENABLE TRIGGER ALL;
ALTER TABLE crpnpccorporationdivisions ENABLE TRIGGER ALL;
ALTER TABLE crpnpccorporationresearchfields ENABLE TRIGGER ALL;
ALTER TABLE crpnpccorporationtrades ENABLE TRIGGER ALL;
ALTER TABLE crpnpccorporations ENABLE TRIGGER ALL;
ALTER TABLE crpnpcdivisions ENABLE TRIGGER ALL;
ALTER TABLE dgmattributecategories ENABLE TRIGGER ALL;
ALTER TABLE dgmattributetypes ENABLE TRIGGER ALL;
ALTER TABLE dgmtypeattributes ENABLE TRIGGER ALL;
ALTER TABLE eveicons ENABLE TRIGGER ALL;
ALTER TABLE eveunits ENABLE TRIGGER ALL;
ALTER TABLE industryactivity ENABLE TRIGGER ALL;
ALTER TABLE invmetagroups ENABLE TRIGGER ALL;
ALTER TABLE invmetatypes ENABLE TRIGGER ALL;
ALTER TABLE invtypematerials ENABLE TRIGGER ALL;
ALTER TABLE dgmeffects ENABLE TRIGGER ALL;
ALTER TABLE dgmexpressions ENABLE TRIGGER ALL;
ALTER TABLE dgmtypeeffects ENABLE TRIGGER ALL;
ALTER TABLE evegraphics ENABLE TRIGGER ALL;
ALTER TABLE industryactivitymaterials ENABLE TRIGGER ALL;
ALTER TABLE industryactivityprobabilities ENABLE TRIGGER ALL;
ALTER TABLE industryactivityproducts ENABLE TRIGGER ALL;
ALTER TABLE industryactivityraces ENABLE TRIGGER ALL;
ALTER TABLE industryactivityskills ENABLE TRIGGER ALL;
ALTER TABLE industryblueprints ENABLE TRIGGER ALL;
ALTER TABLE invcategories ENABLE TRIGGER ALL;
ALTER TABLE invcontrabandtypes ENABLE TRIGGER ALL;
ALTER TABLE invcontroltowerresourcepurposes ENABLE TRIGGER ALL;
ALTER TABLE invcontroltowerresources ENABLE TRIGGER ALL;
ALTER TABLE invflags ENABLE TRIGGER ALL;
ALTER TABLE invgroups ENABLE TRIGGER ALL;
ALTER TABLE invitems ENABLE TRIGGER ALL;
ALTER TABLE invmarketgroups ENABLE TRIGGER ALL;
ALTER TABLE invnames ENABLE TRIGGER ALL;
ALTER TABLE invpositions ENABLE TRIGGER ALL;
ALTER TABLE invtraits ENABLE TRIGGER ALL;
ALTER TABLE invtypereactions ENABLE TRIGGER ALL;
ALTER TABLE maplocationscenes ENABLE TRIGGER ALL;
ALTER TABLE ramassemblylinestations ENABLE TRIGGER ALL;
ALTER TABLE raminstallationtypecontents ENABLE TRIGGER ALL;
ALTER TABLE staservices ENABLE TRIGGER ALL;
ALTER TABLE stastationtypes ENABLE TRIGGER ALL;
ALTER TABLE invtypes ENABLE TRIGGER ALL;
ALTER TABLE invuniquenames ENABLE TRIGGER ALL;
ALTER TABLE invvolumes ENABLE TRIGGER ALL;
ALTER TABLE mapcelestialstatistics ENABLE TRIGGER ALL;
ALTER TABLE mapconstellationjumps ENABLE TRIGGER ALL;
ALTER TABLE mapconstellations ENABLE TRIGGER ALL;
ALTER TABLE mapdenormalize ENABLE TRIGGER ALL;
ALTER TABLE mapjumps ENABLE TRIGGER ALL;
ALTER TABLE maplandmarks ENABLE TRIGGER ALL;
ALTER TABLE maplocationwormholeclasses ENABLE TRIGGER ALL;
ALTER TABLE mapregionjumps ENABLE TRIGGER ALL;
ALTER TABLE mapregions ENABLE TRIGGER ALL;
ALTER TABLE mapsolarsystemjumps ENABLE TRIGGER ALL;
ALTER TABLE mapsolarsystems ENABLE TRIGGER ALL;
ALTER TABLE mapuniverse ENABLE TRIGGER ALL;
ALTER TABLE planetschematics ENABLE TRIGGER ALL;
ALTER TABLE planetschematicspinmap ENABLE TRIGGER ALL;
ALTER TABLE planetschematicstypemap ENABLE TRIGGER ALL;
ALTER TABLE ramactivities ENABLE TRIGGER ALL;
ALTER TABLE ramassemblylinetypedetailpercategory ENABLE TRIGGER ALL;
ALTER TABLE ramassemblylinetypedetailpergroup ENABLE TRIGGER ALL;
ALTER TABLE ramassemblylinetypes ENABLE TRIGGER ALL;
ALTER TABLE skinlicense ENABLE TRIGGER ALL;
ALTER TABLE skinmaterials ENABLE TRIGGER ALL;
ALTER TABLE skinship ENABLE TRIGGER ALL;
ALTER TABLE skins ENABLE TRIGGER ALL;
ALTER TABLE staoperationservices ENABLE TRIGGER ALL;
ALTER TABLE staoperations ENABLE TRIGGER ALL;
ALTER TABLE stastations ENABLE TRIGGER ALL;
ALTER TABLE translationtables ENABLE TRIGGER ALL;
ALTER TABLE trntranslationcolumns ENABLE TRIGGER ALL;
ALTER TABLE trntranslationlanguages ENABLE TRIGGER ALL;
ALTER TABLE trntranslations ENABLE TRIGGER ALL;
ALTER TABLE warcombatzonesystems ENABLE TRIGGER ALL;
ALTER TABLE warcombatzones ENABLE TRIGGER ALL;

